# loki
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: demo
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /data/loki
      storage:
        filesystem:
          chunks_directory: /data/loki/chunks
          rules_directory: /data/loki/rules
      ring:
        kvstore:
          store: inmemory
      replication_factor: 1

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks

    limits_config:
      enforce_metric_name: false

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s

---
# promtail
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: demo
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: http://loki.demo.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods-app-logs
        pipeline_stages:
          - cri: {}
        static_configs:
          - targets:
              - localhost
            labels:
              job: app-logs
              __path__: /var/log/containers/*app-*.log