# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-app-grafana
  namespace: demo
  labels:
    app: app-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-grafana
  template:
    metadata:
      labels:
        app: app-grafana
    spec:
      containers:
        - name: app-grafana
          image: grafana/grafana:9.5.2
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: pvc-grafana
---
# service
apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: demo
  labels:
    app: svc-grafana
spec:
  type: NodePort
  selector:
    app: app-grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32767
      protocol: TCP
      name: http
