# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-stack-loki
  namespace: demo
  labels:
    app: stack-loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stack-loki
  template:
    metadata:
      labels:
        app: stack-loki
    spec:
      containers:
        - name: stack-loki
          image: grafana/loki:2.9.1
          args:
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /data/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
        - name: loki-storage
          persistentVolumeClaim:
            claimName: pvc-loki
---
# service
apiVersion: v1
kind: Service
metadata:
  name: svc-loki
  namespace: demo
  labels:
    app: svc-loki
spec:
  selector:
    app: stack-loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http
