# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: demo
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: loki
          image: grafana/loki:2.9.1
          args:
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /data/loki
      volumes:
        - name: config
          configMap:
            name: loki-config
            items:
              - key: loki.yaml
                path: loki.yaml
        - name: loki-storage
          hostPath:
            path: /var/snap/microk8s/common/default-storage/loki
            type: DirectoryOrCreate
---
# service
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: demo
  labels:
    app: loki
spec:
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
      name: http