package config

type key string

const (
	ENV_TAG key = "ENV_TAG"
	APP_TAG key = "APP_TAG"

	API_PORT       key = "API_PORT"
	API_TIMEOUT    key = "API_TIMEOUT"
	MONGO_USER     key = "MONGO_USER"
	MONGO_PASSWORD key = "MONGO_PASSWORD"
	MONGO_HOST     key = "MONGO_HOST"
	MONGO_DATABASE key = "MONGO_DATABASE"
	RPC_ENDPOINT   key = "RPC_ENDPOINT"
	KAFKA_ADDRS    key = "KAFKA_ADDRS"
	KAFKA_VERSION  key = "KAFKA_VERSION"

	MNEMONIC_STRING   key = "MNEMONIC_STRING"
	MNEMONIC_ACCOUNTS key = "MNEMONIC_ACCOUNTS"

	WATCHDOG_INTERVAL    key = "WATCHDOG_INTERVAL"
	WATCHDOG_BLOCK_RANGE key = "WATCHDOG_BLOCK_RANGE"

	CONSUMER_GROUP_ID    key = "CONSUMER_GROUP_ID"
	CONSUME_MAX_INTERVAL key = "CONSUME_MAX_INTERVAL"
	CONSUME_BATCHSIZE    key = "CONSUME_BATCHSIZE"

	FAUCET_AMOUNT key = "FAUCET_AMOUNT"
	FAUCET_LIMIT  key = "FAUCET_LIMIT"
)

func (k key) String() string {
	return string(k)
}
