apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-service
  namespace: demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-app-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 30