apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongodb
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: microk8s-hostpath
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ganache
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: microk8s-hostpath
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath